# Generated by Django 3.2.5 on 2022-04-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('mingcheng', models.CharField(max_length=25, verbose_name='商品名称')),
                ('jianjie', models.CharField(max_length=128, verbose_name='商品简介')),
                ('type_id', models.SmallIntegerField(choices=[(1, '电脑'), (2, '化妆品'), (3, '水果'), (4, '图书'), (5, '男装女装'), (6, '数据库')], default=1, verbose_name='商品种类')),
                ('xinghao', models.SmallIntegerField(choices=[(1, '小号'), (2, '中号'), (3, '大号')], verbose_name='商品型号')),
                ('status', models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=0, verbose_name='商品状态')),
                ('sales', models.IntegerField(default=0, verbose_name='商品销量')),
                ('stock', models.IntegerField(default=1, verbose_name='商品库存')),
                ('huiyuanjia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='会员价')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='市场价')),
                ('tejia', models.IntegerField(choices=[(1, '小号'), (2, '中号'), (3, '大号')], default=0, verbose_name='是否为特价商品')),
                ('pinpai', models.CharField(max_length=25, verbose_name='商品品牌')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 's_goods',
            },
        ),
    ]
