# Generated by Django 3.2.5 on 2022-04-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='jianjie',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='商品简介'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='xinghao',
            field=models.SmallIntegerField(blank=True, choices=[(1, '小号'), (2, '中号'), (3, '大号')], null=True, verbose_name='商品型号'),
        ),
    ]
