# Generated by Django 3.2.5 on 2022-04-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20220422_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='tejia',
            field=models.IntegerField(choices=[(1, '特价'), (0, '非促销')], default=0, verbose_name='是否为特价商品'),
        ),
    ]
